### ISSUE TITLE
Move to Firestore

### ISSUE THREAD

**Issue by mstijak** [codaxy/tdo#6]
Firestore is a much better alternative to localStorage and GitHub gists. Using Firestore we get authentication options, real-time updates between boards, offline support and possibility to implemet board sharing.
The downside is that user data is not truly private, but anyone can run their own instance of tdo and Fireststore.

**Comment by senpl** [comment]
Why this issue was closed. Is it done?

**Comment by mstijak** [comment]
Yes, this version works with Firestore. However, there are some unresolved issues with the ordering of tasks and boards.
